[project]
name = "rationalizer"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "accelerate>=1.11.0",
    "beautifulsoup4>=4.14.2",
    "django>=5.2.8",
    "feedparser>=6.0.12",
    "gunicorn>=23.0.0",
    "pandas>=2.3.3",
    "protobuf>=6.33.1",
    "requests>=2.32.5",
    "scikit-learn>=1.7.2",
    "sentencepiece>=0.2.1",
    "torch>=2.9.1",
    "transformers>=4.57.1",
    "whitenoise>=6.11.0",
]
