# Generated by Django 5.2.8 on 2025-11-16 18:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalysisRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("articles_collected", models.IntegerField(default=0)),
                ("articles_categorized", models.IntegerField(default=0)),
                ("articles_analyzed", models.IntegerField(default=0)),
                ("authors_profiled", models.IntegerField(default=0)),
                ("date_range_start", models.DateTimeField(blank=True, null=True)),
                ("date_range_end", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-run_date"],
            },
        ),
        migrations.CreateModel(
            name="AuthorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200, unique=True)),
                ("total_articles", models.IntegerField(default=0)),
                ("categorized_articles", models.IntegerField(default=0)),
                ("overall_avg_valence", models.FloatField(default=0.0)),
                ("overall_variance", models.FloatField(default=0.0)),
                ("cross_category_variance", models.FloatField(default=0.0)),
                ("balance_score", models.FloatField(db_index=True, default=0.0)),
                ("balance_rank", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-balance_score"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_id",
                    models.CharField(
                        choices=[
                            ("nuclear_energy", "Nuclear Energy"),
                            ("data_centers", "Data Centers"),
                            ("healthcare", "Healthcare"),
                            ("immigration", "Immigration"),
                            ("technology", "Technology Industry"),
                        ],
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                ("description", models.TextField()),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("url", models.URLField(max_length=1000, unique=True)),
                ("publication", models.CharField(max_length=200)),
                ("domain", models.CharField(max_length=200)),
                (
                    "author",
                    models.CharField(
                        blank=True, db_index=True, max_length=200, null=True
                    ),
                ),
                ("published_date", models.DateTimeField(blank=True, null=True)),
                (
                    "collected_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("content", models.TextField()),
                ("summary", models.TextField(blank=True)),
                ("overall_valence", models.FloatField(db_index=True, default=0.0)),
                ("title_valence", models.FloatField(default=0.0)),
                ("content_valence", models.FloatField(default=0.0)),
                ("sentiment_confidence", models.FloatField(default=0.0)),
                ("sentiment_label", models.CharField(blank=True, max_length=50)),
                (
                    "primary_category",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("primary_confidence", models.FloatField(default=0.0)),
            ],
            options={
                "ordering": ["-published_date"],
                "indexes": [
                    models.Index(
                        fields=["author", "primary_category"],
                        name="dashboard_a_author_04ad68_idx",
                    ),
                    models.Index(
                        fields=["overall_valence"],
                        name="dashboard_a_overall_a6d57a_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuthorCategoryMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("article_count", models.IntegerField(default=0)),
                ("avg_valence", models.FloatField(db_index=True, default=0.0)),
                ("valence_variance", models.FloatField(default=0.0)),
                ("valence_stdev", models.FloatField(default=0.0)),
                ("rank", models.IntegerField(default=0)),
                ("total_in_category", models.IntegerField(default=0)),
                (
                    "most_negative_article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="author_most_negative",
                        to="dashboard.article",
                    ),
                ),
                (
                    "most_positive_article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="author_most_positive",
                        to="dashboard.article",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.authorprofile",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.category",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "avg_valence"],
                "unique_together": {("author", "category")},
            },
        ),
        migrations.CreateModel(
            name="ArticleCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("confidence", models.FloatField(default=0.0)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.article",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.category",
                    ),
                ),
            ],
            options={
                "ordering": ["-confidence"],
                "unique_together": {("article", "category")},
            },
        ),
    ]
