# Generated by Django 5.2.8 on 2025-11-16 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicationProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200, unique=True)),
                ("total_articles", models.IntegerField(default=0)),
                ("categorized_articles", models.IntegerField(default=0)),
                ("overall_avg_valence", models.FloatField(default=0.0)),
                ("overall_variance", models.FloatField(default=0.0)),
                ("cross_category_variance", models.FloatField(default=0.0)),
                ("balance_score", models.FloatField(db_index=True, default=0.0)),
                ("balance_rank", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-balance_score"],
            },
        ),
        migrations.AddField(
            model_name="analysisrun",
            name="publications_profiled",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="category",
            name="category_id",
            field=models.CharField(
                choices=[
                    ("federal_budget", "Federal Budget & National Debt"),
                    ("immigration", "Immigration"),
                    ("gun_control", "Gun Control & Second Amendment"),
                    ("elections", "Elections & Campaign Finance"),
                    ("judiciary", "Judiciary & Supreme Court"),
                    ("foreign_policy", "Foreign Policy & International Trade"),
                    ("federal_reserve", "Federal Reserve & Inflation"),
                    ("labor_employment", "Labor & Employment"),
                    ("supply_chain", "Supply Chain Management"),
                    ("real_estate", "Real Estate & Housing"),
                    ("small_business", "Small Business & Entrepreneurship"),
                    ("ai_regulation", "Artificial Intelligence (AI) Regulation"),
                    ("technology", "Technology Industry"),
                    ("data_centers", "Data Center Development"),
                    ("cybersecurity", "Cybersecurity"),
                    ("semiconductor", "Semiconductor Industry"),
                    ("climate_change", "Climate Change & Policy"),
                    ("energy_transition", "Energy Transition"),
                    ("nuclear_energy", "Nuclear Energy"),
                    ("oil_gas", "Oil & Gas Industry"),
                    ("water_rights", "Water Rights & Scarcity"),
                    ("health_insurance", "Health Insurance & Policy"),
                    ("pharmaceuticals", "Pharmaceuticals & Drug Pricing"),
                    ("public_health", "Public Health"),
                    ("education", "Education (K-12 & Higher Ed)"),
                    ("criminal_justice", "Criminal Justice Reform"),
                    ("social_security", "Social Security & Entitlements"),
                    ("infrastructure", "National Infrastructure"),
                    ("telecommunications", "Telecommunications"),
                    ("aerospace", "Aerospace & Aviation"),
                ],
                max_length=100,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="PublicationCategoryMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("article_count", models.IntegerField(default=0)),
                ("avg_valence", models.FloatField(db_index=True, default=0.0)),
                ("valence_variance", models.FloatField(default=0.0)),
                ("valence_stdev", models.FloatField(default=0.0)),
                ("rank", models.IntegerField(default=0)),
                ("total_in_category", models.IntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.category",
                    ),
                ),
                (
                    "most_negative_article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="publication_most_negative",
                        to="dashboard.article",
                    ),
                ),
                (
                    "most_positive_article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="publication_most_positive",
                        to="dashboard.article",
                    ),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.publicationprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "avg_valence"],
                "unique_together": {("publication", "category")},
            },
        ),
    ]
